name: browser-activity
on:
  push:
  schedule:
    # Weekly on Saturdays at 15:10.
    - cron: '10 15 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'yarn'
    - name: setup-yarn
      run: npm install -g yarn
    - name: fetch-dependencies
      run: yarn
    - name: build
      run: yarn build
    - name: lint
      run: yarn lint
